### ISSUE TITLE
Great work! Consider using published case reports for training?

### ISSUE THREAD

**Issue by drqiaojin** [starmpcc/CAMEL#1]
First, thank you for sharing this great work!

Just wondering if pre-training on published case reports interests you. We have [PMC-Patients](https://huggingface.co/datasets/zhengyun21/PMC-Patients), an open dataset consisting of 167k patient summaries extracted from case reports in PubMed Central.

These summaries are of high-quality, containing admission, labs, diagnosis, treatment, progression and follow-up data. Each note is about 400 words long.

Could be valuable for tuning your model.

**Comment by sean0042** [comment]
Thank you for your interest in our research.

We are definitely interested in using PMC-Patients dataset either on pre-training or generating instructions.

Thanks for the recommendation!
