### ISSUE TITLE
A Collaboration Request from Lung Cancer Physician

### ISSUE THREAD

**Issue by zuhgeng** [starmpcc/CAMEL#5]
I am a thoracic surgeon at the Affiliated Hospital of Huazhong University of Science and Technology in China. My main research is the intersection of lung cancer and artificial intelligence. Recently I want to do chatgpt content and I want to cooperate with you. If you are interested, please contact me to discuss. E-mail: gengzuhan@126.com

**Comment by sean0042** [comment]
Thank you for your interest in our work. We will contact you separately.
