### ISSUE TITLE
Uploading the model to physionet

### ISSUE THREAD

**Issue by hanyin88** [starmpcc/CAMEL#6]
Hello there and thanks for the super impressive work!

I was hoping to ask about any updates on uploading the model to physionet? I am hoping to reference your model in a downstream task on a current research work. 

Many thanks!:)

**Comment by starmpcc** [comment]
Currently, our submission to PhysioNet is still under review, so I'm afraid we can't share it publicly just yet. 
However, if you could provide us with proof of your PhysioNet credentials, we might be able to send over the checkpoint via email. 

Thanks you for your attention!

**Comment by hanyin88** [comment]
> Currently, our submission to PhysioNet is still under review, so I'm afraid we can't share it publicly just yet. However, if you could provide us with proof of your PhysioNet credentials, we might be able to send over the checkpoint via email.
> 
> Thanks you for your attention!

That would be awesome and deeply appreciate the kind accommodation. Wondering what's the best way to send the credentials over? Would be happy to share it via email or whatever way you see fit. :) My email is hanyinw2@illinois.edu.

**Comment by aleguma** [comment]
Hi, 

Great work! I would like to ask if there is any news regarding the uploading of the model to Physionet. We are interested in using your model and referencing it in our ongoing research.

Thank you!

**Comment by starmpcc** [comment]
Unfortunately, we have halted the PhysioNet submission and replaced it with our new model, Asclepius. This is an instruction-tuned model based on clinical notes, and it empirically demonstrates superior performance compared to CAMEL. You can directly access Asclepius on [HuggingFace](https://huggingface.co/starmpcc/Asclepius-7B).

However, if you still wish to access the CAMEL checkpoint, please provide your PhysioNet credentials to me (kjune0322@kaist.ac.kr).

Thank you for your interest in our project!
